### ISSUE TITLE
Check ideas

### ISSUE THREAD

**Issue by gaborcsardi** [MangoTheCat/goodpractice#1]
## `DESCRIPTION` file 
- [x] `URL`
- [x] `BugReports`
- [x] No `Depends`
- [x] No `Date`
- [x] ~~Valid fields (`R CMD check` does most of this)~~ `R CMD check` does it
- [x] ~~No whitespace from DESCRIPTION field names~~ `R CMD check` does it
- [x] ~~No blank lines from DESCRIPTION~~ `R CMD check` does it

## `NAMESPACE` file

- [x] No `import` (only import functions)
- [x] No `exportPattern`
- [x] Related: all external functions are called via `::`. See #41.

## Code complexity

- [x] Functions are short (number of expressions) See #42
- [x] Lines are short (number of expressions) See #42
- [x] Total amount of code is reasonable See #42
- [x] All internal functions are used See #42
- [x] Cyclomatic complexity
- [x] Argument order is consistent between functions See #43

## Functions to avoid

- [x] `attach`
- [x] `setwd`
- [x] `sapply`
- [x] `library/require`

## Expressions to avoid

- [x] `1:length(x)`

## Packages to avoid

- [x] `multicore`, use `parallel` instead. See #44

## Documentation

- [x] There is a README or package level docs See #45
- [x] Manual pages for exported functions See #45
- [x] Manual pages for internal functions See #45
- [x] All arguments documented See #45
- [x] Manual pages have examples See #45
- [x] NEWS file See #45
- [x] Return values are documented. `R CMD check` does not catch this, actually. See #45

## Tests

- [x] Test cases OK See #46    
- [x] Test cases code coverage

## Code style

- [x] ~~Conforms to a standard~~ Hard to check in general, so closing now.

## R CMD check 

- [x] Report all problems

**Comment by HenrikBengtsson** [comment]
Somewhat related: [Wish #16: `R CMD check --flavor=<flavor>`: customized add-on package validation](https://github.com/HenrikBengtsson/Wishlist-for-R/issues/16).

**Comment by gaborcsardi** [comment]
@HenrikBengtsson Looks great, thanks! `goodpractice` will definitely have flavours, actually it already has something, I called it "styles", flavour is a better word I think.

**Comment by HenrikBengtsson** [comment]
BTW, is your check list in top box suggestion it is bad to specify `Date:` in your DESCRIPTION, cf. "No Date"?

**Comment by gaborcsardi** [comment]
YEs, it is bad to specify `Date`, that's what I meant.

**Comment by HenrikBengtsson** [comment]
Why?

**Comment by gaborcsardi** [comment]
Goes out of date often because people don't update it, and it is not a required field. Another date field is put in automatically by `R CMD build`. 


But again, this is subjective, and in your flavour you can turn it on and off as you like.

**Comment by HenrikBengtsson** [comment]
> Goes out of date often because people don't update it, and it is not a required field.

Yes, I agree outdated `Date:` info is useless.  Recently(?), `R CMD check --as-cran` started to report on this:
```
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'John Doe <johndoe@example.com>'
The Date field is over a month old.
* checking package namespace information ... OK
```

> Another date field is put in automatically by R CMD build.

True, but on the other hand the `Packaged:` field also change whenever the otherwise identical source is rebuilt.  

I was mostly curious on your take on this, so nothing important to me.   I like to be able to see when a package was "touched" by the developer (info that should be self contained).  The `Date:` field provides that info if maintained.  An alternative, which I actually prefer, is that the NEWS file provides a date with every version entry.  This gives further information how old "old" is, because the perception of time varies widely between version numbering formats and developers.  Unfortunately, not all packages provide dates in `NEWS`.

I'm experimenting moving away from `Date:` in some of my packages and only keeping that info in `NEWS`.  The reason for that is mostly to save me a few keystrokes having to update `Date:`.

**Comment by peterhurford** [comment]
I'd really like to see a linter that goes through all the functions in your package and ensures that (1) they are prefixed and that (2) they are declared in your DESCRIPTION file.  Also should ensure there are no `library` or `require` calls.  I don't know if `lintr` or `R CMD CHECK` does that already?

**Comment by gaborcsardi** [comment]
@peterhurford `library()` and `require` calls are picked up by `R CMD check`, so we get those automatically.

What do you mean about functions being prefixed? Can you give an example?

I am also not sure about declaring functions in `DESCRIPTION`. You mean packages, maybe?

**Comment by peterhurford** [comment]
@gaborcsardi 

> library() and require calls are picked up by R CMD check, so we get those automatically.

Ah, awesome. :+1: 

> What do you mean about functions being prefixed? Can you give an example?

Like making sure you call `goodpractice::gp` instead of `gp` from within your package. I think this may already be covered by R CMD CHECK.

> I am also not sure about declaring functions in DESCRIPTION. You mean packages, maybe?

Haha, yeah, I meant packages.

**Comment by gaborcsardi** [comment]
> Like making sure you call goodpractice::gp instead of gp from within your package. I think this may already be covered by R CMD CHECK.

That is not strictly compulsory if you import the function via NAMESPACE. (Or the whole package, although that is not suggested.) But it is true that explicit calls can be a legitimate requirement, and then we can check for this, yes. I'll add it above.

> Haha, yeah, I meant packages.

That is checked by `R CMD check`, too, I think.

**Comment by peterhurford** [comment]
Came here to suggest you check for code coverage, but I see you already have that. :+1: 

Other idea: any plan to integrate with https://github.com/jimhester/lintr?

**Comment by gaborcsardi** [comment]
Yes, we will call `lintr` as well.

**Comment by drisso** [comment]
Bioconductor has the BiocCheck package that performs some useful checks (here: https://github.com/Bioconductor/BiocCheck).
A lot of Bioconductor specific checks not relevant here, but some useful, like check direct slot access for S4 objects, use of <<- and browser().

**Comment by gaborcsardi** [comment]
@drisso :+1:

**Comment by eribul** [comment]
Not sure I like this advice my self (I don't follow it so far ...) but I recently picked up (through discussion during UseR2016) that the use of `x$y` is considered bad practice for non interactive use, where `x[["y"]]` should actually be preffered.

One reason is motivated by the following (as stated by Hadley):
```{r}
> a <- data.frame(xyz = 1)
> a$x
[1] 1
> a[["x"]]
NULL
> 
```

**Comment by gaborcsardi** [comment]
@eribul `R CMD check` already catches partial names IMO, so we have that already I think. Let me know if we don't catch it.

**Comment by gaborcsardi** [comment]
Closing this now. I opened separate issues for the remaining ones.
