### ISSUE TITLE
Checks: documentation

### ISSUE THREAD

**Issue by gaborcsardi** [MangoTheCat/goodpractice#45]
- [ ] There is a README or package level docs See #45
- [ ] Manual pages for exported functions See #45
- [ ] Manual pages for internal functions See #45
- [ ] All arguments documented See #45
- [ ] Manual pages have examples See #45
- [ ] NEWS file See #45
- [ ] Return values are documented. `R CMD check` does not catch this, actually. See #45
